obj-m += Helloworld.o

PWD := $(shell pwd)
CROSS=/home/truong/workspace/kernelbuildscripts/dl/gcc-10.5.0-nolibc/arm-linux-gnueabi/bin/arm-linux-gnueabi-
KER_DIR=/home/truong/workspace/kernelbuildscripts/KERNEL

all:
	make ARCH=
clean:
